### ISSUE TITLE
Do the papers in this dataset have anything in common with those in the semantic scholar?

### ISSUE THREAD

**Issue by HelloRusk** [allenai/scidocs#15]
Hello, I have a simple question.

I'm wondering whether the SCIDOCS papers are part of Semantic Scholar data. In my view this is the important point since  both SciBERT and SPECTER are trained using that data.

**Comment by armancohan** [comment]
Good question. SciDocs excludes papers that were used in training of SPECTER. 
But we didn't explicitly control for overlap of SciDocs with SciBERT pre-training data.

**Comment by HelloRusk** [comment]
I get it. Thanks!
