### ISSUE TITLE
Mapping to S2ORC IDs

### ISSUE THREAD

**Issue by malteos** [allenai/scidocs#18]
Hi,

thanks for sharing this dataset. Is there any kind of mapping from the `paper_id` used in this dataset to the S2ORC IDS without querying the S2 API? 

PS: Am I correct that each `paper_id` corresponds to the S2 API IDs?

Cheers
malte

**Comment by sergeyf** [comment]
Hi Malte,

Glad you are finding it useful!

Pretty sure you're right on both counts: (a) we don't have a mapping available for this dataset and (b) they are corpus ids.  You can tell by length. For example:

Corpus ID:
https://api.semanticscholar.org/CorpusID:221703107

Same paper but the URL has the PDF hash instead:
https://www.semanticscholar.org/paper/It's-Not-Just-Size-That-Matters%3A-Small-Language-Are-Schick-Schutze/f30444fbb6ad806168e2564db4815cd27faa7fd9

**Comment by malteos** [comment]
Thanks. So the `paperId` in Semantic Scholar is just the PDF hash? And why are different IDs pointing to the same paper? For example:

- https://api.semanticscholar.org/v1/paper/00014a8515491f0b3fe2a1ff6e0f5305e584dcd9
- https://api.semanticscholar.org/v1/paper/cae94aba8be24101c624a43342d615824f80b859

**Comment by sergeyf** [comment]
It means we mapped different PDFs (from probably different sources) to the same paper object.
