### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'allennlp': 'allennlp'

### ISSUE THREAD

**Issue by ZzyChris97** [allenai/scidocs#21]
I followed your instrucation but got this error!

**Comment by ZzyChris97** [comment]
And i check my env, find there is allennlp0.9 in it

**Comment by sergeyf** [comment]
Would you be so kind as to open this issue on the AllenNLP repo? Tell them how you installed AllenNLP and ask why it might not be working. I don't have any insights on my end. If you do find a solution, please post it here for others who may suffering similar issues.

**Comment by ZzyChris97** [comment]
> Would you be so kind as to open this issue on the AllenNLP repo? Tell them how you installed AllenNLP and ask why it might not be working. I don't have any insights on my end. If you do find a solution, please post it here for others who may suffering similar issues.

**OK! I try to run the command in the terminal：**
allennlp train /root/code/python/share/scidocs/data/recomm/train_similar_papers_model.json -s /root/code/python/share/scidocs/data/recomm-tmp --include-package scidocs.recommender

**the error didn't show again, but i got a new runtimeError:**

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/scidocs/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/usr/local/anaconda3/envs/scidocs/lib/python3.7/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/usr/local/anaconda3/envs/scidocs/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/usr/local/anaconda3/envs/scidocs/lib/python3.7/site-packages/allennlp/commands/train.py", line 124, in train_model_from_args
    args.cache_prefix)
  File "/usr/local/anaconda3/envs/scidocs/lib/python3.7/site-packages/allennlp/commands/train.py", line 162, in train_model_from_file
    params = Params.from_file(parameter_filename, overrides)
  File "/usr/local/anaconda3/envs/scidocs/lib/python3.7/site-packages/allennlp/common/params.py", line 490, in from_file
    file_dict = json.loads(evaluate_file(params_file, ext_vars=ext_vars))
RuntimeError: RUNTIME ERROR: undefined external variable: jsonlines_embedding_format
	/root/code/python/share/scidocs/data/recomm/train_similar_papers_model.json:22:50-90	thunk <s>
	/root/code/python/share/scidocs/data/recomm/train_similar_papers_model.json:2:6	thunk <a>
	/root/code/python/share/scidocs/data/recomm/train_similar_papers_model.json:2:6-17	function <anonymous>
	/root/code/python/share/scidocs/data/recomm/train_similar_papers_model.json:2:6-17	function <stringToBool>
	/root/code/python/share/scidocs/data/recomm/train_similar_papers_model.json:22:37-91	object <anonymous>
	/root/code/python/share/scidocs/data/recomm/train_similar_papers_model.json:(17:23)-(23:6)	object <anonymous>

Do you have any idea? Thanks a lot!

**Comment by sergeyf** [comment]
Since it's an AllenNLP error, could you please ask in the AllenNLP github repo? I have no idea unfortunately. It doesn't look like anything I've ever seen.

**Comment by ZzyChris97** [comment]
> Since it's an AllenNLP error, could you please ask in the AllenNLP github repo? I have no idea unfortunately. It doesn't look like anything I've ever seen.

That's all right, i have asked in the AllenNLP and got no reply yet.  And Can i ask some details about the recomm evaluateion?
* I get the embedding of every article and then shuold i use cosine similarity to get a rank list ? and how can i evaluate the rank result
*  I saw the function of the allennlp seems like to train a model for recomm, if i accomplish by myself do you have some advice or details?

I'm sorry to bother you again and again!

**Comment by sergeyf** [comment]
If you just want to run the recom evaluation, please use the provided utilities: https://github.com/allenai/scidocs/blob/1fceacdecd158eb40ab091c74fb66768b55900d3/scidocs/recomm_click_eval.py#L120

The repo isn't designed to be used otherwise really.

**Comment by ZzyChris97** [comment]
After my try i think i have figure out this issue.

the reason of `FileNotFoundError: [Errno 2]` is the subprocess, one way to solve this is to set shell = True
```subprocess.run(command, shell=True)```

Though, i still met some problem, is seem like some problem with my conda env, and finally i solved it all by: 
1. running the command firstly and get the model.tar.gz rather than use subprocess, some details i list below:
    * I set the parameters directly in the **train_similar_papers_model.json** 
      like change ```local EMBEDDINGS_PATH = std.extVar("EMBEDDINGS_PATH");``` to ```local EMBEDDINGS_PATH = 'data/specter-embeddings/recomm.jsonl';```
    * And then run the command ```allennlp train /root/code/python/share/scidocs/data/recomm/train_similar_papers_model.json -s /root/code/python/share/scidocs/data/recomm-tmp --include-package scidocs.recommender```

2. secondly, run the ```get_recomm_metrics()``` function, and get the result. Some changes i list below:
    * annotate the code `# subprocess.run(command)`
    * annotate the code `# shutil.rmtree(serialization_dir, ignore_errors=True)` 


Finally, I still want to thank the author for each patient reply！

**Comment by sergeyf** [comment]
Thanks for posting your solution. Glad it all worked out.
