### ISSUE TITLE
About the training examples of the recommendation task

### ISSUE THREAD

**Issue by cenyk1230** [allenai/scidocs#25]
Thank you for sharing the SciDocs.

I downloaded the dataset via the script `aws s3 sync --no-sign-request s3://ai2-s2-research-public/specter/scidocs/ data/`.
But I find that the number of training examples of the recommendation task is only 4000, which is not consistent with the reported number (20K) in the [SPECTER paper](https://arxiv.org/pdf/2004.07180.pdf). Is there anything wrong about the number?

![image](https://user-images.githubusercontent.com/12823252/190982369-f14e9622-65c9-48aa-ae9f-9f06611fa8e6.png)

**Comment by sergeyf** [comment]
Hello @cenyk1230. Looks like you found a paper bug. 4000 is the right size, but we forgot to update it in the paper. It was 20k in an earlier version of SciDocs. Our apologies!
